// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Automation_Laboratory_Backend.Models
{
    public partial class AutomationlaboratorydbContext : DbContext
    {
        public AutomationlaboratorydbContext()
        {
        }

        public AutomationlaboratorydbContext(DbContextOptions<AutomationlaboratorydbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Workplace> Workplaces { get; set; }

       
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Device>(entity =>
            {
                entity.HasOne(d => d.Workplace)
                    .WithMany(p => p.Devices)
                    .HasForeignKey(d => d.WorkplaceId)
                    .HasConstraintName("FK_Device_Workplace");
            });

            modelBuilder.Entity<History>(entity =>
            {
                entity.Property(e => e.Time)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<Module>(entity =>
            {
                entity.HasOne(d => d.Device)
                    .WithMany(p => p.Modules)
                    .HasForeignKey(d => d.DeviceId)
                    .HasConstraintName("FK_Module_Device");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}