// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Automation_Laboratory_Backend.Models
{
    [Table("Device")]
    public partial class Device
    {
        public Device()
        {
            Modules = new HashSet<Module>();
        }

        public long? WorkplaceId { get; set; }
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string DeviceCode { get; set; }
        [StringLength(50)]
        public string Versio { get; set; }
        [StringLength(50)]
        public string DeviceName { get; set; }
        [StringLength(50)]
        public string BootUp { get; set; }
        [StringLength(50)]
        public string Firmware { get; set; }
        [StringLength(50)]
        public string MAC { get; set; }
        [StringLength(50)]
        public string ProfinetIP { get; set; }
        [StringLength(50)]
        public string Subnet { get; set; }
        [StringLength(50)]
        public string RouterIP { get; set; }
        [StringLength(50)]
        public string Profibus { get; set; }
        [StringLength(50)]
        public string ASI { get; set; }
        [StringLength(50)]
        public string MPI { get; set; }
        [StringLength(50)]
        public string CounterIn { get; set; }
        [StringLength(50)]
        public string CounterOut { get; set; }
        public bool IsActive { get; set; } = true;

        [ForeignKey(nameof(WorkplaceId))]
        [InverseProperty("Devices")]
        public virtual Workplace Workplace { get; set; }
        [InverseProperty(nameof(Module.Device))]
        public virtual ICollection<Module> Modules { get; set; }
    }
}