// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Automation_Laboratory_Backend.Models
{
    [Keyless]
    [Table("History")]
    public partial class History
    {
        public byte[] Time { get; set; }
        [StringLength(50)]
        public string Action { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
    }
}