// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Automation_Laboratory_Backend.Models
{
    [Table("Module")]
    public partial class Module
    {
        [StringLength(50)]
        public string SignalIn { get; set; }
        [StringLength(50)]
        public string SignalOut { get; set; }
        [Key]
        public long Id { get; set; }
        public long? DeviceId { get; set; }

        [ForeignKey(nameof(DeviceId))]
        [InverseProperty("Modules")]
        public virtual Device Device { get; set; }
    }
}