// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Automation_Laboratory_Backend.Models
{
    [Table("Workplace")]
    public partial class Workplace
    {
        public Workplace()
        {
            Devices = new HashSet<Device>();
        }

        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string DisplayName { get; set; }

        [InverseProperty(nameof(Device.Workplace))]
        public virtual ICollection<Device> Devices { get; set; }
    }
}